config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :competitions
      resources :competitors
      resources :weight_records
      resources :users
      resources :admin_users

      root to: "competitions#index"
    end
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'competitions/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'competitions#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'sign_out' => 'devise/sessions#destroy'
  end

  resources :competitions do
    resources :weight_records
  end
  resources :enrollments, only: [:create, :destroy, :update]
end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :competitors
  has_many :weight_records, dependent: :destroy
  has_many :users, through: :weight_records
end

app/controllers/admin/competitions_controller.rb
module Admin
  class CompetitionsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  include CompetitionsHelper
  before_action :authenticate_user!

  def index
    @competitions = Competition.all
  end

  def show
    @competition = Competition.find(params[:id])
  end

  def new
    @competition = Competition.new
  end

  def create
    @competition = current_user.competitions.build(competition_params)

    if @competition.save
      flash[:success] = "Competition '#{@competition.title}' created!"
      redirect_to @competition
    else
      flash[:alert] = "Some error!"
      render 'new'
    end
  end

  def edit
    @competition = Competition.find(params[:id])
    flash[:alert] = "You do not have access to this page"
    redirect_to @competition
  end

  private

  helper_method def earliest_and_latest_weight_record_by_user
    @earliest_and_latest_weight_record_by_user || begin
     @competition.weight_records.preload(:user).default_order.group_by(&:user).map do |user, weight_records|
      [
        user,
        {
          earliest: weight_records.last,
          latest: weight_records.first
        }
      ]
     end.to_h
    end
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
  def competition_params
    params.require(:competition).permit(:title, :start_date, :finish_date)
  end
end

app/views/competitions/_form.html.erb
<%= form_with(model: @competition, local: true) do |f| %>
  <div class="container">
    <div class="title">
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title, class: "form-control", placeholder: "Enter the Competition Title", autofocus: true %>
    </div>

    <div class="start-date">
      <%= f.label :start_date, class: "form-label" %>
      <%= f.date_field :start_date, type: "date", class: "form-control" %>
    </div>

    <div class="finish-date">
      <%= f.label :finish_date, class: "form-label" %>
      <%= f.date_field :finish_date, type: "date", class: "form-control" %>
    </div>

    <div class="submit-cancel">
      <%= f.submit "Create Competition", class:"btn btn-success" %>
      <%= link_to 'Cancel',root_path, class:"btn btn-danger" %>
    </div>
  </div>
<% end %>

app/views/competitions/index.html.erb
<div class="container">
  <h2>Competitions</h2>
  <%= link_to 'New Competition', new_competition_path(), class: "btn btn-success" %>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Start Date</th>
          <th>Finish Date</th>
        </tr>
      </thead>
      <tbody>
        <% @competitions.each do |competition| %>
          <tr>
            <td><%= link_to competition.title, competition_path(competition) %></td>
            <td><%= competition.start_date %></td>
            <td><%= competition.finish_date %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/competitions/new.html.erb
<div class="container">
  <h2 class="title">Create Competition</h2>
  <%= render 'form' %>
</div>

app/views/competitions/show.html.erb
<div class="container">
  <h2><%= @competition.title %></h2>
  <%= link_to 'New Weight Record', new_competition_weight_record_path(@competition), class: "btn btn-success" %>

  <div>
    <span class="badge bg-secondary"><%= @competition.start_date %> to <%= @competition.finish_date %></span>
  </div>

  <%= line_chart @competition.weight_records.group_by(&:user).map { |user, weight_records|
      {name: user.name, data: weight_records.pluck(:effective_date, :weight)}
  } %>

  <div class="container">
    <h2>Competitors</h2>
    <div class="table-responsive">
      <table class="table" id="sortTable">
        <thead>
          <tr>
            <th data-field="name">Competitor</th>
            <th data-field="weight">Starting Weight</th>
            <th data-field="weight">Most Recent Weight</th>
            <th data-field="weight">Difference</th>
            <th data-field="weight">Percent Lost</th>
          </tr>
        </thead>
        <tbody>
          <% earliest_and_latest_weight_record_by_user.each do |user, weight_records| %>
            <% earliest = weight_records[:earliest] %>
            <% latest = weight_records[:latest] %>
            <tr>
              <td><%= user.name %></td>
              <td><%= earliest.weight %>kg</td>
              <td><%= latest.weight %>kg</td>
              <td><%= latest.weight - earliest.weight %>kg</td>
              <td><%= ((100 - (latest.weight / earliest.weight) * 100)).round(2) %>%</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <br/>

  <div class="container">
    <h2>Weigh Ins</h2>
    <div class="table-responsive">
      <table class="table" id="sortTable">
        <thead>
          <tr>
            <th data-field="date" data-sortable="true" >Date</th>
            <th data-field="name">Competitor</th>
            <th data-field="weight">Weight</th>
            <th data-field="action">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @competition.weight_records.preload(:user).default_order.each do |record| %>
            <tr>
              <td><%= record.effective_date %></td>
              <td><%= record.user.name %></td>
              <td><%= record.weight %></td>
              <% wr = record.id %>
              <% puts wr%>
              <% if record.user_id == current_user.id %>
                <td><%= link_to 'Edit', edit_competition_weight_record_path(@competition.id, record.id), class: "btn btn-success btn-sm" %>
                <%= link_to 'Delete', competition_weight_record_path(@competition.id, record.id), data: { confirm: "Are you sure?" }, :method => :delete, class: "btn btn-danger btn-sm" %></td>
              <% else %>
                <td></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>