config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :competitions
      resources :competitors
      resources :weight_records
      resources :users
      resources :admin_users

      root to: "competitions#index"
    end
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'competitions/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'competitions#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'sign_out' => 'devise/sessions#destroy'
  end

  resources :competitions do
    resources :weight_records
  end
  resources :enrollments, only: [:create, :destroy, :update]
end

app/helpers/navigation_helper.rb
module NavigationHelper

  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end

end

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li ><%= link_to 'Log In', login_path %></li>
<li ><%= link_to 'Sign Up', signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="dropdown pc-menu">
  <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
    <span id="user-name"><%= current_user.name %></span>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
    <% if current_user.type == "AdminUser" %>
      <li><%= link_to 'Admin', admin_root_path %></li>
    <% end %>
  </ul>
</li>

<li class="mobile-menu">
  <%= link_to 'Edit Profile', edit_user_registration_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
</li>
<li class="mobile-menu">
  <% if current_user.type == "AdminUser" %>
    <%= link_to 'Admin', admin_root_path %>
  <% end %>
</li>